### ISSUE TITLE
Error: The file “swift-package-list” couldn’t be opened because there is no such file

### ISSUE THREAD

**Issue by hoppsen** [FelixHerrmann/swift-package-list#104]
Would love to try out your tool, but regardless of the installation method I get the same error (see below). You got any idea? I double checked the `$PATH` already but this seems fine.

Version: `4.0.1`

### Mint
```bash
mint run swift-package-list Test.xcodeproj
Error: The file “swift-package-list” couldn’t be opened because there is no such file.
```

### Homebrew
```bash
swift-package-list Test.xcodeproj
Error: The file “swift-package-list” couldn’t be opened because there is no such file
```

### Xcode Build Plugin
```bash
Run script build phase 'SwiftPackageListPlugin' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked.

PhaseScriptExecution SwiftPackageListPlugin <HIDDEN>

Error: The file “swift-package-list” couldn’t be opened because there is no such file.
LLVM Profile Error: Failed to write file "default.profraw": Operation not permitted
Command PhaseScriptExecution failed with a nonzero exit code

Error: The file “swift-package-list” couldn’t be opened because there is no such file.

LLVM Profile Error: Failed to write file "default.profraw": Operation not permitted

Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by FelixHerrmann** [comment]
Hey, thanks for your interest!

Sounds like an issue on specifically your machine/environment.

Can you try to download the latest version manually (https://github.com/FelixHerrmann/swift-package-list/releases/download/4.0.1/swift-package-list.tar.gz) and execute it directly with `./swift-package-list` so we can ensure it has nothing to do with the executable? The output of `which swift-package-list` would also be interesting.
