### ISSUE TITLE
AppKit not being found

### ISSUE THREAD

**Issue by noloman** [FelixHerrmann/swift-package-list#109]
Hi,

Thanks a lot for this Swift package first of all!

I just integreated in my iOS app, and unfortunately I'm unable to make it work, as I'm getting an error in `PDFGenerator` complaining with `No such module AppKit`.

I following the steps in the README installing it via Homebrew, then generating the `package-list.json`, adding it to the Xcode project and adding the build phase.

Have I done something incorrectly? I've currently imported all three packages (the binary too) when adding your package dependency to my project.

Thanks!

**Comment by FelixHerrmann** [comment]
Hey, thanks for being interested!

The binary target should not be added to your normal codebase, just remove it again in your target's General section and you should be good; let me know if that worked!

**Comment by noloman** [comment]
> Hey, thanks for being interested!
> 
> The binary target should not be added to your normal codebase, just remove it again in your target's General section and you should be good; let me know if that worked!

That's right man, thanks a lot! This is great! 😄

**Comment by FelixHerrmann** [comment]
Np, good to hear that!
