### ISSUE TITLE
Unable to build iOS target after adding SwiftPackageList 

### ISSUE THREAD

**Issue by tarrouye** [FelixHerrmann/swift-package-list#129]
Hi ! I'm having some issues integrating this library.

Here are the steps I took:

1. Add `swift-package-list` to my project using SPM
2. Add both `swift-package-list` and `SwiftPackageListUI` to my target
3. Add the build plugin under Build Phases > Run Build Tool Plug-ins
4. Trust the plugin
5. Try to build

And I got an error related to importing AppKit in `PDFGenerator.swift`

![image](https://github.com/user-attachments/assets/44564b9c-3b3c-46c9-8067-f6cd2772556e)

Have I done something wrong with my setup ? Thanks !

**Comment by FelixHerrmann** [comment]
Hey @tarrouye, the executable product (`swift-package-list`) should not be added to the target, just remove that and you should be good to go!

**Comment by tarrouye** [comment]
Thank you @FelixHerrmann ! Silly me. Super helpful library <3

**Comment by FelixHerrmann** [comment]
No worries @tarrouye, this is a common question.
