### ISSUE TITLE
Build script phase not working

### ISSUE THREAD

**Issue by eschos24** [FelixHerrmann/swift-package-list#27]
First of all, thank you for making this! It works beautifully when I run it from the terminal! 

Unfortunately, I have not been able to get it to work as a build script phase. I installed swift-package-list on my machine beforehand, but it still doesn't work. I also tried adding it as a package dependency to my project, but that also didn't work. Either way it gives the warning "swift-package-list not installed". I am just using an xcodeproj, not xcworkspace. I'm happy to give any additional details that might be helpful. Thank you!

**Comment by FelixHerrmann** [comment]
Hi, let's get this working!

I guess that you have installed it via Mint? Xcode's PATH variable does not contain the path to Mint's bin directory. So you can easily fix this by adding `export PATH="$PATH:$HOME/.mint/bin/"` as the first line in your build script or link the swift-package-list file to your standard bin directory by executing `ln -s $HOME/.mint/bin/swift-package-list /usr/local/bin/swift-package-list` in your Terminal (probably with sudo). Let me know if that worked!

FYI, adding the package as dependency has no effect on the writing process, this is only for a convenient way to read/display the contents of the generated file.

**Comment by FelixHerrmann** [comment]
Hey @eschos24 let me know if that works so I can close the issue!

**Comment by eschos24** [comment]
Yes, that worked! Thank you so much. 

One other note, my project has a " " (space) in the name, so I had to adjust the script slightly (in addition to wanting it to generate the settings bundle). Just in case it's helpful, here my final script that is working:
```
export PATH="$PATH:$HOME/.mint/bin/"

if command -v swift-package-list &> /dev/null; then
    OUTPUT_PATH=$SOURCE_ROOT/$TARGETNAME
    
    swift-package-list "$PROJECT_FILE_PATH" --output-path "$OUTPUT_PATH" --requires-license --file-type settings-bundle
else
    echo "warning: swift-package-list not installed"
fi
```

**Comment by FelixHerrmann** [comment]
Oh yea, you're totally right, will update that in the docs!
