### ISSUE TITLE
Build phase - Build input files cannot be found

### ISSUE THREAD

**Issue by JulesMoorhouse** [FelixHerrmann/swift-package-list#28]
Hi,

I added the SPM, added the executable and the ui...

I assumed I didn't have to install (Aka using mint) as I used the SPM ?

Added the build phase and I'm getting this error...

`error: Build input files cannot be found: '/Users/jm/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphoneos/ArgumentParser.o', '/Users/jm/Library/Developer/Xcode/DerivedData/Build/Products/Debug-iphoneos/ArgumentParserToolInfo.o' (in target 'swift-package-list' from project 'SwiftPackageList')`

Any ideas ?

Thanks,

Jules.

**Comment by FelixHerrmann** [comment]
Hi Jules,

You have to install it on your machine, either manually or via Mint as described [here](https://github.com/FelixHerrmann/swift-package-list#installation). The package is only for reading the generated file conveniently!

Let me know if something is still unclear!

**Comment by JulesMoorhouse** [comment]
Ah ok...

I needed to added `export PATH="$PATH:$HOME/.mint/bin/"` as mentioned in the other issue.

So the build phase now runs... but I don't seem to be getting any output.
I do have spms with licenses...

Any ideas ?

Jules.

**Comment by FelixHerrmann** [comment]
Cool, did you add the file to your project/target as described in step 6 and 7?

**Comment by JulesMoorhouse** [comment]
No I mean it didn't create a file.

**Comment by JulesMoorhouse** [comment]
Oh hang on, I had the first checkout checked....
Now I have the original error 🙁

**Comment by JulesMoorhouse** [comment]
<img width="615" alt="image" src="https://user-images.githubusercontent.com/361024/168440135-6d041d4b-8f8b-431d-8b4a-3ff52598827f.png">

🤦‍♂️

**Comment by FelixHerrmann** [comment]
> Oh hang on, I had the first checkout checked....
> Now I have the original error 🙁

Hmm, what happens if you execute the command manually in your Terminal? I should generate it on your desktop.

**Comment by FelixHerrmann** [comment]
> <img alt="image" width="615" src="https://user-images.githubusercontent.com/361024/168440135-6d041d4b-8f8b-431d-8b4a-3ff52598827f.png">
> 
> 🤦‍♂️

This looks fine 🤔

**Comment by JulesMoorhouse** [comment]
Yeah, it's in the path, so why doesn't it work when ran from the sh script Xcode creates.

If I remove the if statement and just run the two lines, it fails with the same error.

**Comment by JulesMoorhouse** [comment]
it runs fine from my home folder too... hmmm

**Comment by FelixHerrmann** [comment]
Xcode provides it's own environment and the PATH variable where the mint bin folder is added is not the one from your system...

Both methods described in #27 should work, what happens when you try the second method where you create an alias to mint's swift-package-list with `ln -s $HOME/.mint/bin/swift-package-list /usr/local/bin/swift-package-list`?

**Comment by JulesMoorhouse** [comment]
Awesome, working :)

**Comment by FelixHerrmann** [comment]
Awesome!!
