### ISSUE TITLE
Add customFileName Option

### ISSUE THREAD

**Issue by JulesMoorhouse** [FelixHerrmann/swift-package-list#29]
Hi,

I'd like to be able to specify the output file name.

Can't see that in the options, just the path?

Thanks,

Jules.

**Comment by FelixHerrmann** [comment]
Definitely can add this Option!

**Comment by JulesMoorhouse** [comment]
No hurry....

`    mv "$OUTPUT_PATH/package-list.plist" "$OUTPUT_PATH/../Acknowledgements.plist"`

Works for now.

**Comment by FelixHerrmann** [comment]
That's smart!

Pretty much done already 😀

**Comment by FelixHerrmann** [comment]
Hey @JulesMoorhouse, just wanted to let you know that this is now available with the latest [release](https://github.com/FelixHerrmann/swift-package-list/releases/tag/2.0.0)!

The command option is `--custom-file-name` and all the libraries have now an optional `fileName` parameter.
