### ISSUE TITLE
No such module 'AppKit'

### ISSUE THREAD

**Issue by JulesMoorhouse** [FelixHerrmann/swift-package-list#30]
Hi,

I have an iOS project and am using the  `AcknowledgmentsList` from `SwiftPackageListUI`.

I've selected the ..
```
SwiftPackageListUI
Swift-Package-List
```
.. spm packages...

However, I'm getting an error from the `PDFBuilder`

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/361024/168442339-dc09ddc1-cdcd-43db-8d70-9357e60d50b3.png">

As the error mentions, think it needs and if statement etc...

Jules.

**Comment by FelixHerrmann** [comment]
Hey, do not add the SwiftPackageListCommand library to any of your targets, this is only exposed as an executable product for Mint!

**Comment by JulesMoorhouse** [comment]
Oh ok...
I was using `https://github.com/MartinP7r/AckGen` it allows you to use the executable via the spm, hence my confusion.
Having said that I have recently been having problems the the path of the executable.

That fixed it. 👍

**Comment by FelixHerrmann** [comment]
Gotcha 👍
