### ISSUE TITLE
SwiftPackageListUI AcknowledgmentsList() - shows no licenses

### ISSUE THREAD

**Issue by JulesMoorhouse** [FelixHerrmann/swift-package-list#31]
Hi,

Sorry to be so much trouble....

However, I have a `package-list.plist` with licenses in it..

But nothing showing in the UI.

<img width="434" alt="image" src="https://user-images.githubusercontent.com/361024/168443060-0644ca9e-56cf-4bb1-912e-0cd9d177ee25.png">

I don't think I can see any logs on the Xcode debug..

Any ideas?

Jules.

**Comment by FelixHerrmann** [comment]
Haha, no problem!

Do you see any results when you use the [packageList function](https://github.com/FelixHerrmann/swift-package-list#swiftpackagelist-1)?

**Comment by JulesMoorhouse** [comment]
Ahhh.. forgot the add the plist to the project... just going off to hide under a rock... :|

Rather than setup yet another issue, is there anyway, I can change the style of the `Licenses` section header or remove it ?
I'm happy to put this in a new issue, if you'd rather...

**Comment by FelixHerrmann** [comment]
This happens to the best... 😂

Let me investigate the custom header thing, can you give me a bit more context why and how you want to change it?

**Comment by JulesMoorhouse** [comment]
It just doesn’t fit with standard SwiftUI layout.

Looks like a style you’d see many iOS versions ago.

I’d be happy just not to have it at all.

**Comment by FelixHerrmann** [comment]
You can use the [listStyle(_:)](https://developer.apple.com/documentation/swiftui/view/liststyle(_:)) modifier on AcknowledgmentsList 🤔

**Comment by JulesMoorhouse** [comment]
I have tried basically copying the contents `AcknowledgmentsList` but I think `internal` is stopping me using view models etc.

**Comment by JulesMoorhouse** [comment]
Nice `.listStyle(InsetGroupedListStyle())` fits well 👍 

Thanks, think everything is working.

I do have a FontAwesome license I need to add, but I think I might have to create an empty package...

**Comment by FelixHerrmann** [comment]
👍

> I do have a FontAwesome license I need to add, but I think I might have to create an empty package...
That actually would work, maybe I'll add support for custom licenses in the future but I don't want to make things too complex... nobody is forced to use the pre-build UI components
