### ISSUE TITLE
Feature request: Support for -clonedSourcePackagesDirPath

### ISSUE THREAD

**Issue by notapplicableio** [FelixHerrmann/swift-package-list#41]
First of all, love this software :)

If I run `xcodebuild -resolvePackageDependencies` with an additional argument of `-clonedSourcePackagesDirPath ~/Packages` swift-package-list cannot find the `workspace-state.json`.

Enhancement

In addition to `--derived-data-path` can you also provide an alternative `--source-packages-data-path` to override this?

Rationale

- Some CI scenarios benefit from clearing derived data, so xcodebuild provides the ability to resolve packages to a different location.

Is this a feature you could add, please?

**Comment by FelixHerrmann** [comment]
Yea I can add that option! :)

**Comment by FelixHerrmann** [comment]
[`2.1.0`](https://github.com/FelixHerrmann/swift-package-list/releases/tag/2.1.0) is live now, let me know if everything works as expected!

**Comment by notapplicableio** [comment]
Sorry, I don't think I ever saw this. Thank you.
