### ISSUE TITLE
Dependency Tree is missing

### ISSUE THREAD

**Issue by JD-CSTx** [FelixHerrmann/swift-package-list#44]
The `Swift Package Manager` can show you a Dependency-Tree. But that works only on **packages** directly, _not_ on projects. So you can _never_ see a Dependency-Tree for your project.

If this tool could build a Depdency-Tree for your **project**, that would be fantastic.

I build a script for that, but having it in your tool would be better, especially since I don't have your experience and am not 100% sure if that's 100% resistent against edge-cases:
``` bash
if [[ $1 == "" ]]; then
  echo "Missing build dir as 1st parameter"
  exit 1
fi

if [[ $2 == "" ]]; then
  echo "Missing project dir as 2nd parameter"
  exit 1
fi

BUILD_DIR=$1
PROJECT_DIR=$2

echo "Build dependencies tree"
cd "$BUILD_DIR/../../SourcePackages/checkouts"
exportFile="$PROJECT_DIR/dependencies-tree.md"
echo "# Dependencies trees for each Swift-Package" > "$exportFile"
echo "" >> "$exportFile"
echo "Build date: $(date '+%Y-%d-%m %a %H:%M:%S %Z')" >> "$exportFile"
echo "" >> "$exportFile"
for directory in */; do
  echo "Tree for $directory"
  echo "" >> "$exportFile"
  echo "## Tree for $directory" >> "$exportFile"
  pushd $directory
  swift package show-dependencies >> "$exportFile"
  echo "" >> "$exportFile"
  echo "" >> "$exportFile"
  popd
done
```

**Comment by FelixHerrmann** [comment]
Hey @JD-CSTx, thanks for the idea! I think [this new CLI tool](https://github.com/simonbs/dependency-graph) is exactly what you are looking for.

**Comment by JD-CSTx** [comment]
> Hey @JD-CSTx, thanks for the idea! I think [this new CLI tool](https://github.com/simonbs/dependency-graph) is exactly what you are looking for.

Thanks, but I need a compact overview, which the swift package manager already delivers in an ideal format.
The output of that tool looks horribly confusing.

**Comment by FelixHerrmann** [comment]
Gotcha @JD-CSTx!

In my opinion this functionality does not fit 100% into this tool because 1. the main purpose is to get a file which lists all packages and 2. it just relies on files/directories instead of executing other CLI commands. However, it should be very easy for you to make your own tool with the logic of your bash script.
