### ISSUE TITLE
Support for Tuist Projects

### ISSUE THREAD

**Issue by myak0v1ev** [FelixHerrmann/swift-package-list#69]
Hello. Thanks for your great tool. 

I have a suggestion to add some improvements to your tool. 
For now, we can define the path to xcodeproj/xcworkspace because we need the `Package.resolved` file.
But for now, in iOS community, teams are using Tuist to configure their project. With using Tuist you don't have `Package.resolved` file like other standard projects. Instead, you have a `.package.resolved` file that creates by Tuist when you setup the project.

What do you think about it?

**Comment by myak0v1ev** [comment]
I found an easy solution to handle it.
After Tuist generated `.package.resolved` file, I can just move it to `xcshareddata/swiftpm/Package.resolved` before running `swift-package-list` command. 

But if you see that it's the valid flow that can be handled by your tool it would be nice to add it.

**Comment by FelixHerrmann** [comment]
Hey @myak0v1ev, as you can see I have added Tuist support which can be now tested on the `release/4.0` branch. It works for me with the latest version of Tuist (3.37.0) on a simple project but it would be good if you can give it a shot via pulling the branch and [install it from source](https://github.com/FelixHerrmann/swift-package-list/tree/release/4.0#installing-from-source).

For Tuist projects the entry point is the `Project.swift` file; there are some more changes in `release/4.0` so make sure you specify the desired options. A good example could be `swift-package-list Project.swift --output-type json --output-path ~/Desktop` which will generate _~/Desktop/package-list.json_.

**Comment by myak0v1ev** [comment]
@FelixHerrmann Hey. Thanks. I'll try and give you feedback on it.
